### ISSUE TITLE
Read text file and create object

### ISSUE THREAD

**Issue by CKarlslund** [Maladict/LifeCycleBank#2]
Alla kunder och konton lagras i en textfil. När programmet startas läses angiven textfil in med data
och alla objekt skapas. Använd args-parameter i Main-metoden för filnamnet.
Det finns filer med data på studentportalen som du ska kunna läsa in och filen du skapar ska ha samma
format. (Tips! Läs på mer om ToString och Parse som kan ta fler parametrar som styr hur tal och
datum formateras och tolkas. Kolla in InvariantCulture som ofta används för import och export.)

**Comment by mariakallstrom** [comment]
Jag har gjort att metoden i classen läser från bankdata-small och delar upp informationen i 2 objektlistor. En CustomerList och en AccountList.

**Comment by mariakallstrom** [comment]
Nu läser den från den fil med senaste datum.
