### ISSUE TITLE
GetCustomerInfo(int accountNumber)

### ISSUE THREAD

**Issue by CKarlslund** [Maladict/LifeCycleBank#5]
Det ska gå att ta fram en kundbild genom att ange kundnummer. Kundbilden ska visa all information
om kunden och alla kundens konton. Kundbilden ska också visa det totala saldot för kunden genom att
summera saldot på kundens konton.
Det ska gå att söka efter kund på namn eller postort. En lista ska visas med kundnummer och namn.

**Comment by sTaMiNa01** [comment]
Skapade metoderna:
public static ICustomer GetCustomer(IBank bank, int customerNumber) och 
public static List<IAccount> GetCustomerAccounts(IBank bank,int customerID) för att kunna visa kundbilden. För att kunna söka på kunden skapade jag: public static List<ICustomer> SearchCustomer(IBank bank,string searchWord). Dessa metoder ligger i CustomerService under service mappen i LifeCycleBank.csproj projektet.
